/* AdministrativeAreas */
create table ADMINISTRATIVEAREA (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(3),
	NID		NUMERIC,
	POL_LCD		NUMERIC(5),
	PRIMARY KEY (CID, TABCD, LCD)
);

/* Classes */
create table CLASSES (
	CLASS	CHAR(1),
	PRIMARY KEY (CLASS)
);

/* Countries */
create table COUNTRIES (
	CID	NUMERIC(3),
	CCD	CHAR(1),
	CNAME	CHAR(50),
	ECC	CHAR(2),
	PRIMARY KEY (CID, CCD, ECC)
);

/* ERNo_belongs_to_country */
create table ERNO_BELONGS_TO_CO (
	CID	NUMERIC(3),
	ENO	CHAR(10)
);

/* EuroRoadNo */
create table EUROROADNO (
	ENO		CHAR(10),
	ECOMMENT	CHAR(100),
	PRIMARY KEY (ENO)
);

/* Intersections */
create table INTERSECTIONS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	INT_CID		NUMERIC(3),
	INT_TABCD	NUMERIC(2),
	INT_LCD		NUMERIC(5)
);

/* Languages */
create table LANGUAGES (
	CID		NUMERIC(3),
	LID		NUMERIC(2),
	LANGUAGE	CHAR(25),
	PRIMARY KEY (CID, LID)
);

/* Locationcodes */
create table LOCATIONCODES (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	ALLOCATED	NUMERIC(1),
	PRIMARY KEY (CID, TABCD, LCD)
);

/* LocationDataSets */
create table LOCATIONDATASETS (
	CID			NUMERIC(3),
	TABCD			NUMERIC(2),
	DCOMMENT		CHAR(100),
	VERSION			CHAR(7),
	VERSIONDESCRIPTION	CHAR(100),
	PRIMARY KEY (CID, TABCD)
);

/* Names */
create table NAMES (
	CID		NUMERIC(3),
	LID		NUMERIC(2),
	NID		NUMERIC,
	NAME		CHAR(100),
	NCOMMENT	CHAR(100),
	PRIMARY KEY (CID, LID, NID)
);

/* NameTranslations */
create table NAMETRANSLATIONS (
	CID		NUMERIC(3),
	LID		NUMERIC(2),
	NID		NUMERIC,
	NTRANSLATION	CHAR(100),
	PRIMARY KEY (CID, LID, NID)
);

/* OtherAreas */
create table OTHERAREAS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(3),
	NID		NUMERIC,
	POL_LCD		NUMERIC(5),
	PRIMARY KEY (CID, TABCD, LCD, CLASS, TCD, STCD)
);

/* Poffsets */
create table POFFSETS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	NEG_OFF_LCD	NUMERIC(5),
	POS_OFF_LCD	NUMERIC(5),
	PRIMARY KEY (CID, TABCD, LCD)
);

/* Points */
create table POINTS (
	CID			NUMERIC(3),
	TABCD			NUMERIC(2),
	LCD			NUMERIC(5),
	CLASS			CHAR(1),
	TCD			NUMERIC(3),
	STCD			NUMERIC(5),
	JUNCTIONNUMBER		CHAR(10),
	RNID			NUMERIC,
	N1ID			NUMERIC,
	N2ID			NUMERIC,
	POL_LCD			NUMERIC(5),
	OTH_LCD			NUMERIC(5),
	SEG_LCD			NUMERIC(5),
	ROA_LCD			NUMERIC(5),
	INPOS			NUMERIC(1),
	INNEG			NUMERIC(1),
	OUTPOS			NUMERIC(1),
	OUTNEG			NUMERIC(1),
	PRESENTPOS		NUMERIC(1),
	PRESENTNEG		NUMERIC(1),
	DIVERSIONPOS		CHAR(10),
	DIVERSIONNEG		CHAR(10),
	XCOORD			CHAR(9),
	YCOORD			CHAR(8),
	INTERRUPTSROAD		NUMERIC(1),
	URBAN			NUMERIC(1),
	PRIMARY KEY (CID, TABCD, LCD, CLASS, TCD, STCD)
);

/* Road_network_level_types */
create table ROAD_NETWORK_LEVEL_TYPES (
	PES_LEV		NUMERIC(1),
	PES_LEV_DESC	CHAR(5),
	TDESC		CHAR(50),
	PRIMARY KEY (PES_LEV)
);

/* Roads */
create table ROADS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(5),
	ROADNUMBER	CHAR(10),
	RNID		NUMERIC,
	N1ID		NUMERIC,
	N2ID		NUMERIC,
	POL_LCD		NUMERIC(5),
	PES_LEV		NUMERIC(1),
	PRIMARY KEY (CID, TABCD, LCD, CLASS, TCD, STCD)
);

/* Seg_has_ERNo */
create table SEG_HAS_ERNO (
	CID	NUMERIC(3),
	TABCD	NUMERIC(2),
	LCD	NUMERIC(5),
	ENO	CHAR(10),
	PRIMARY KEY (CID, TABCD, LCD)
);

/* Segments */
create table SEGMENTS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(5),
	ROADNUMBER	CHAR(10),
	RNID		NUMERIC,
	N1ID		NUMERIC,
	N2ID		NUMERIC,
	ROA_LCD		NUMERIC(5),
	SEG_LCD		NUMERIC(5),
	POL_LCD		NUMERIC(5),
	PRIMARY KEY (CID, TABCD, LCD, CLASS, TCD, STCD)
);

/* Soffsets */
create table SOFFSETS (
	CID		NUMERIC(3),
	TABCD		NUMERIC(2),
	LCD		NUMERIC(5),
	NEG_OFF_LCD	NUMERIC(5),
	POS_OFF_LCD	NUMERIC(5),
	PRIMARY KEY (CID, TABCD, LCD)
);

/* Subtypes */
create table SUBTYPES (
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(5),
	SDESC		CHAR(50),
	SNATCODE	CHAR(5),
	SNATDESC	CHAR(50),
	PRIMARY KEY (CLASS, TCD, STCD)
);

/* SubtypeTranslation */
create table SUBTYPETRANSLATION (
	CID		NUMERIC(3),
	LID		NUMERIC(2),
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	STCD		NUMERIC(5),
	STRANSLATION	CHAR(100),
	PRIMARY KEY (CID, LID, CLASS, TCD, STCD)
);

/* Types */
create table TYPES (
	CLASS		CHAR(1),
	TCD		NUMERIC(3),
	TDESC		CHAR(50),
	TNATCD		CHAR(5),
	TNATDESC	CHAR(50),
	PRIMARY KEY (CLASS, TCD)
);
