.TH "rdsradiocapture" 1 "Thi May 26 2011" "rdsradiocapture"

.SH NAME
rdsradiocapture \- Save songs using information from RT+ (item toggle/running/title/artist)

.SH SYNOPSIS
.B rdsradiocapture

.SH DESCRIPTION
Save songs using information from RT+ (MP3-ID3v2-Tags):
 * item toggle/running
 * RT+ 1: ITEM.TITLE
 * RT+ 2: ITEM.ALBUM
 * RT+ 3: ITEM.TRACKNUMBER
 * RT+ 4: ITEM.ARTIST
 * RT+ 5: ITEM.COMPOSITION
 * RT+ 6: ITEM.MOVEMENT
 * RT+ 7: ITEM.CONDUCTOR
 * RT+ 8: ITEM.COMPOSER
 * RT+ 9: ITEM.BAND
 * RT+ 10: ITEM.COMMENT
 * RT+ 11: ITEM.GENRE
 * RT+ 39: PROGRAMME.HOMEPAGE
 * RT+ 61: IDENTIFIER (according to Interational Standard Recording Code, available at http://www.ifpi.org/isrc/)
 * RT+ 62: PURCHASE

.SH FILES

.SH AUTHORS
Tobias Lorenz <tobias.lorenz@gmx.net>

.SH SEE ALSO

